### ISSUE TITLE
PDF export doesn't show on Plattform

### ISSUE THREAD

**Issue by HannnahPue** [mint-o-badges/badgr-ui#736] opened 2024-09-30 12:45 UTC
PDF export (Vorschau) doesn't show up in my badges

**Describe the bug**
when clicking on Rucksack, then selecting one random badge and then clicking on the three dots to show / export the badge PDF the PDF doesn't show. 
![Bildschirmfoto 2024-09-30 um 14 37 48](https://github.com/user-attachments/assets/019b64e8-d654-4bac-a4db-d187d0f0d503)

**To Reproduce**

1. Go to 'rucksack'
2. Click on 'any badge in the rucksack' then the three dots, then "PDF exportieren"

**Expected behavior**
PDF Vorschau should show up.

**Screenshots**

**Desktop (please complete the following information; remove if not applicable):**

-   OS: [Mac Book Pro, Sonoma 14.5
-   Browser [safari]
-   Version [17.5

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
Add any other context about your observations here.

**Comment by HannnahPue** [comment] 2024-09-30 12:46
...the download itself works fine by the way. Just the preview doesn´t

**Comment by zven** [comment] 2024-10-07 08:34
duplicate of https://github.com/mint-o-badges/badgr-ui/issues/701 (already fixed and released)

**Closed by zven** 2024-10-07 08:34 UTC
Labels: test finding
