### ISSUE TITLE
bulk list is not self explanatory 

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#487] opened 2024-07-15 10:08 UTC
**Name the test case**
Bulk-award a badge with the CSV File

**Describe the bug**
The excel-file that is downloaded as an example has some things that could be more explanatory in order make it easier for issuers. 

**Expected behavior**
1. Please rename the CSV file OEBBulkIssueTemplate
2. Please give first and last name in the list: e.g. Peter Meier 
**3. in my opinion the cell for "evidence" is not needed - is that correct??** 
-- I attach a file for you that is exactly like the three points I mentioned, you could use this one, I my points are correct ;)

[oebBulkIssueTemplate.csv](https://github.com/user-attachments/files/16232985/oebBulkIssueTemplate.csv)

**Comment by zven** [comment] 2024-07-26 09:30
duplicate of https://github.com/mint-o-badges/badgr-ui/issues/486

**Closed by zven** 2024-07-26 09:30 UTC
Labels: enhancement, test finding
