### ISSUE TITLE
issue participation badge: error notification

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#583] opened 2024-08-06 12:31 UTC
now I got an error notification when trying to issue a participation badge as well: 
![Bildschirmfoto 2024-08-06 um 14 28 58](https://github.com/user-attachments/assets/3b57d4d0-02bd-43f0-88c9-76d64eafe1c3)

**Comment by zven** [comment] 2024-08-30 10:06
@Annicelia Am I assuming correctly that this is outdated?

**Comment by Annicelia** [comment] 2024-09-09 10:28
@zven yes. But it would be great if the checkbox and the corresponding text could be centered to each other again ;) today it looks like this: 
![Bildschirmfoto 2024-09-09 um 12 25 22](https://github.com/user-attachments/assets/d3dcffca-ce51-47d0-8f5f-d861d98e442c)

**Comment by zven** [comment] 2024-11-15 11:34
outdated and possible duplicate of https://github.com/mint-o-badges/badgr-ui/issues/814

**Closed by zven** 2024-11-15 11:34 UTC
Labels: test finding
