### ISSUE TITLE
Adding a tag doesn't work

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#151] opened 2024-04-05 08:22 UTC
**Name the test case**
Create a badge

**Describe the bug**
While creating a badge I want to add a tag. I type in a tag, that does not exist yet. I click on Hinzufügen, thinking that my tag is added, but I don't get any feedback, if that worked or not. Also I don't see any tags that already exist. That is highly confusing. 

**Expected behavior**
I start typing in the field. Autofill will start to show me the options that match my typed letters. If there is no tag existing, I can add my tag by clicking in Hinzufügen. I get a positive feedback, that my tag was added. I see the tag displayed as a tag within my badge creation view. 

**Screenshots**
<img width="1177" alt="Screenshot 2024-04-05 at 10 18 07" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/e44ff801-2489-4835-a730-e317a370d645">

**Desktop (please complete the following information; remove if not applicable):**
 - OS: [MacOS 
 - Browser chrome

**Comment by zven** [comment] 2024-04-08 11:23
Duplicate of: https://github.com/mint-o-badges/badgr-ui/issues/109

**Closed by zven** 2024-04-08 11:23 UTC
Labels: test finding
