### ISSUE TITLE
Safari doesn't load visuals

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#320] opened 2024-05-21 09:02 UTC
**Name the test case**
Using OEB Website in Safari on Laptop browser - it seems to work on my phone

**Describe the bug**
Safari won't load the website correctly 

**To Reproduce**
Go to OEB Website in Safari

**Screenshots**
![Screenshot 2024-05-21 at 09 50 18](https://github.com/mint-o-badges/badgr-ui/assets/164329233/05616880-13ea-4f71-a9e8-4c16dfddd64d)

**Comment by zven** [comment] 2024-05-21 12:02
duplicate of #328

**Closed by zven** 2024-05-21 12:02 UTC
Labels: test finding
