### ISSUE TITLE
"Old" Blue in every Headline; "Old" Blue and/or not rounded corners of buttons 

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#170] opened 2024-04-08 14:10 UTC
![Bildschirmfoto 2024-04-08 um 16 08 27](https://github.com/mint-o-badges/badgr-ui/assets/164371483/1f808bed-0ec9-4232-88e9-caa48bd37ac4)
![Bildschirmfoto 2024-04-08 um 16 05 31](https://github.com/mint-o-badges/badgr-ui/assets/164371483/19cd1826-587b-497f-8fec-e1d8f0f054d1)
![Bildschirmfoto 2024-04-08 um 16 05 19](https://github.com/mint-o-badges/badgr-ui/assets/164371483/4172733e-8f22-40bd-86f3-64c88a85d60d)
![Bildschirmfoto 2024-04-08 um 16 05 12](https://github.com/mint-o-badges/badgr-ui/assets/164371483/89b7bc73-5f46-4350-bf2f-69fd13eb8b0c)
![Bildschirmfoto 2024-04-08 um 16 04 29](https://github.com/mint-o-badges/badgr-ui/assets/164371483/26477030-319f-4cdb-a782-990a11486751)

- The new blue is: #492E98 (darker/more purple)
- The corner radius of buttons should be 10 (like in the figma file)

MacOS Browser Firefox

**Comment by zven** [comment] 2024-04-08 14:33
Duplicate of #130 (and simply not published while you were testing, @Annicelia)

**Comment by zven** [comment] 2024-04-08 14:34
Duplicate of #130 (and simply not published while you were testing, @Annicelia)

**Closed by zven** 2024-04-08 14:34 UTC
Labels: test finding
