### ISSUE TITLE
Reset password does not work 

### ISSUE THREAD

**Issue by JuliaKleeberger** [mint-o-badges/badgr-ui#311] opened 2024-05-17 13:10 UTC
**Name the test case**
Reset password does not work 

**Describe the bug**
When I want to reset the password I always get the message "Your password must be uncommon and at least 8 characters. Please try again." I tried several different versions, e.g. with special characters and numbers - and without - but it never works ... 

**To Reproduce**

1. Go to 'Sign In'
2. Click on 'Passwort vergessen' 
3. Click on Link in Email to reset password 
4. Enter a new password 

**Expected behavior**
the new password should be accepted; otherwise the error message should be more detailed, that I know what to do / what to change. 

**Screenshots**
![image](https://github.com/mint-o-badges/badgr-ui/assets/12052169/40328ad0-ef09-471d-b7cd-af41af6f5d94)

**Desktop (please complete the following information; remove if not applicable):**

-   OS: [e.g. Windows 10, MacOS 14.03, Ubuntu]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
Add any other context about your observations here.

**Comment by zven** [comment] 2024-05-21 12:05
duplicate of https://github.com/mint-o-badges/badgr-server/issues/107 (and already fixed there)

**Closed by zven** 2024-05-21 12:05 UTC
Labels: test finding
