### ISSUE TITLE
Badge Picture is not generated

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#343] opened 2024-05-24 08:37 UTC
**Name the test case**
creating a Badge (Teilnahme or Kompetenz)

**Describe the bug**
creating a Badge (Teilnahme or Kompetenz) using an icon doesn't create the predefined badge picture in the background. only by choosing first a picture and then changing to an icon creates to frame. 

**To Reproduce**

Go to create a badge
choose Teilnahme or Kompetenz
use the icon library to create the visual 
see that there is no frame around it
go back and use a picture - frame is created - switching back to icon the frame stays

**Expected behavior**

**Screenshots**
![Screenshot 2024-05-24 at 10 24 29](https://github.com/mint-o-badges/badgr-ui/assets/164329233/7e0f42e8-0fc5-4f85-8653-b355fe84660a)

![Screenshot 2024-05-24 at 10 24 17](https://github.com/mint-o-badges/badgr-ui/assets/164329233/b177c842-b39b-461b-911a-61267ff77e61)

**Desktop (please complete the following information; remove if not applicable):**

-   OS
-   Browser [safari]

**Comment by zven** [comment] 2024-05-27 09:22
@schmidfranzi Curious, seems to be a specific Safari problem

**Comment by zven** [comment] 2024-05-27 09:30
After reloading the badge creation page and again uploading an image, it frame is added.

**Comment by zven** [comment] 2024-06-20 12:49
duplicate of #409

**Closed by zven** 2024-06-20 12:49 UTC
Labels: bug, test finding
