### ISSUE TITLE
server: awarding badges on staging does not work anymore

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#234] opened 2024-04-18 12:30 UTC
Something stopped wordking along the way.

![Image](https://github.com/mint-o-badges/badgr-ui/assets/2930332/600c927c-9771-4d80-a45f-66429581d3d5)

**Comment by zven** [comment] 2024-04-18 13:36
Assumption: The Django update broke something in our backend

**Comment by YouQam** [comment] 2024-04-18 18:14
This issue occurred due to using code formatter which added a newlines within blocks. It was resolved by removing all newlines with blocks.
Since this ticket was created as a UI ticket while the issue is a server related, I couldn't line the PR which you can find _here](https://github.com/mint-o-badges/badgr-server/pull/77).

**Closed** 2024-04-22 08:21 UTC
