### ISSUE TITLE
Wrong frame for badge creation/editing

### ISSUE THREAD

**Issue by TobiSchumacher** [mint-o-badges/badgr-ui#183] opened 2024-04-08 16:07 UTC
**Name the test case**
Wrong frame.

**Describe the bug**
After I already created a badge for my institution, as soon as I try to edit it (see screenshot 1) or try to create another badge (see screenshot 2) the old hexagon frame is shown instead of the new frames.

**Screenshots**

Screenshot 1
![Screenshot_20240408-180509](https://github.com/mint-o-badges/badgr-ui/assets/164183217/3f30a32f-9f06-4e85-ae96-227c5e361a25)

Screenshot 2
![Screenshot_20240408-183044](https://github.com/mint-o-badges/badgr-ui/assets/164183217/802374c9-3548-4254-98ef-0da19d9517b0)

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: Huawei Mate 10 Lite
-   OS: Android
-   Browser: Firefox

**Comment by TobiSchumacher** [comment] 2024-04-08 16:39
When I closed my browser, reopened it again, went to OEB and tried to create a new badge, this problem did not occur anymore. Trying to reproduce it, as I am not entirely sure, what exactly I did before the wrong frame was show and will post updates as soon as I got more information.

**Comment by zven** [comment] 2024-04-09 11:19
@TobiSchumacher We fixed that already ;-)

**Comment by zven** [comment] 2024-04-09 11:20
Duplicate of #127

**Closed by zven** 2024-04-09 11:20 UTC
Labels: test finding
