### ISSUE TITLE
Screen Scaling

### ISSUE THREAD

**Issue by HannnahPue** [mint-o-badges/badgr-ui#273] opened 2024-05-02 13:43 UTC
![Image](https://github.com/mint-o-badges/badgr-ui/assets/168734729/d7746665-26fa-4a1d-addc-17b7bab4bfa9)

Safari Browser does not adapt Homepage when scaling the screen

**Comment by zven** [comment] 2024-05-02 13:48
Duplicate of #139

**Closed by zven** 2024-05-02 13:48 UTC
Labels: test finding
