### ISSUE TITLE
testing / development instance without PRs

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-ui#365] opened 2024-05-29 12:46 UTC

**Comment by timber-they** [comment] 2024-05-29 13:24
I already made the necessary code changes and created a server as duplicate of staging, which should then be available under develop.openbadges.education, but Christopher has yet to create the subdomain entry.

**Comment by timber-they** [comment] 2024-05-29 13:27
[This PR](https://github.com/mint-o-badges/badgr-server/pull/128) of the backend also relates to this ticket.

**Comment by zven** [comment] 2024-06-03 11:20
Subdomain should be added now

**Comment by timber-they** [comment] 2024-06-04 13:33
@jona159 you seem to have forgotten to review the [backend PR](https://github.com/mint-o-badges/badgr-server/pull/128)

**Closed** 2024-06-04 13:38 UTC

**Comment by timber-they** [comment] 2024-06-04 13:48
There was a typo, so now there's another [PR](https://github.com/mint-o-badges/badgr-ui/pull/378)
