### ISSUE TITLE
UI: Adding manual competencies

### ISSUE THREAD

**Issue by TobiSchumacher** [mint-o-badges/badgr-ui#175] opened 2024-04-08 15:12 UTC
**Name the test case**
I tried to add competencies manually

**Describe the bug**
The UI looks somewhat unorganized (see screenshot)

**To Reproduce**

**Expected behavior**
have the three cells on top of the screenshot be organized properly (and not with Dauer Kompetenz-Erwerb below the two others) 

**Screenshots**

![Screenshot_20240408-170147](https://github.com/mint-o-badges/badgr-ui/assets/164183217/d788eb2b-099f-458e-a79e-db185d4fe1e2)

-   Device: Huawei Mate 10 Lite (mobile phone)
-   OS: Android 8.0.0.360
-   Browser: Firefox

**Comment by zven** [comment] 2024-04-08 15:35
Closely related to #149

**Comment by zven** [comment] 2024-04-11 14:45
Duplicate of #149

**Closed by zven** 2024-04-11 14:45 UTC
Labels: enhancement, test finding
