### ISSUE TITLE
productive: error notification edit badge

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#584] opened 2024-08-06 16:21 UTC
on productive: when editing the visual of a competency badge, it is not possible to save this due to an error notification: 
![Bildschirmfoto 2024-08-06 um 18 18 17](https://github.com/user-attachments/assets/dee555c7-4dd6-45bb-b69c-0077f3068a6e)

**Comment by timber-they** [comment] 2024-08-09 15:47
I can't reproduce this. I tried editing the badge from your screenshot with my account and it works on prod. To which (kind of) icon did you try to change the visual? Did you remove the frame or something similar? Did you select an icon or an image from your PC? And can you actually still reproduce this yourself? @Annicelia

**Comment by jona159** [comment] 2024-08-13 09:42
The issue occured before the last release, should be fixed by now

**Closed by jona159** 2024-08-13 09:42 UTC
Labels: test finding
