### ISSUE TITLE
Scaling of browser window doesn´t work

### ISSUE THREAD

**Issue by HannnahPue** [mint-o-badges/badgr-ui#274] opened 2024-05-02 14:03 UTC
Screen scaling

**Describe the bug**
When opening our website the content doesn´t adapt in size and position when changing the size if the browser window. eg when viewing the homepage on a smaller screen only party of the web content is visible. Scaling doesn´t work.

**To Reproduce**

1. Go to our website
2. Chance scale of window

**Expected behavior**
Content should scale down or up when changing the size of the window.

![Bildschirmfoto 2024-05-02 um 15 34 59](https://github.com/mint-o-badges/badgr-ui/assets/168734729/ad612566-7e43-4b17-8182-b1a12eadc46e)

![Bildschirmfoto 2024-05-02 um 16 01 46](https://github.com/mint-o-badges/badgr-ui/assets/168734729/bbfea8cd-f105-45f7-b058-ba9a32796a2f)

**Screenshots**

**Desktop (please complete the following information; remove if not applicable):**
Desktop
MAC OS Sonoma 14.4.1
Safari 17.4.1

**Additional context**
Add any other context about your observations here.

**Comment by zven** [comment] 2024-05-02 14:09
Duplicate of #139

**Closed as not planned by zven** 2024-05-02 14:09 UTC
Labels: test finding
