### ISSUE TITLE
badge editor: info: max. size of own visual

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#710] opened 2024-09-18 11:13 UTC
please add the information that uploaded badge images can have a maximum size of 150 kb:
![Bildschirmfoto 2024-09-18 um 13 09 48](https://github.com/user-attachments/assets/a1117fb7-dd8c-46bf-8c2a-159231161332)

**Comment by zven** [comment] 2024-09-27 11:23
duplicate of #628

**Closed by zven** 2024-09-27 11:23 UTC
Labels: test finding
