### ISSUE TITLE
Badge erstellen process is confusing

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#150] opened 2024-04-05 08:11 UTC
**Name the test case**
Badge erstellen

**Describe the bug**
The process and the interface for Badge erstellen is not clear. We should use the wireframes that Annika provides to make the typo readable (at the moment white on pale purple is not readable). and to make the user not enter the Kurzbeschreibung doubled.

**Comment by IngaSchmidt** [comment] 2024-04-05 12:07
In addition: The participation badge also displays the heading competencies
<img width="680" alt="image" src="https://github.com/mint-o-badges/badgr-ui/assets/164493443/5430f290-1181-41b8-b783-79676a19ec2c">

**Comment by zven** [comment] 2024-05-07 19:52
Duplicate of #196

**Closed by zven** 2024-05-07 19:52 UTC
Labels: test finding
