### ISSUE TITLE
Badge creation: can't pick icon on cell phone

### ISSUE THREAD

**Issue by TobiSchumacher** [mint-o-badges/badgr-ui#184] opened 2024-04-08 16:18 UTC
**Name the test case**
Badge creation bug on cell phone

**Describe the bug**
When I create a badge on my cell phone, I can't choose an icon and when I don't click on "Kamera" or "Dateien" (screenshot 1), the badge creation process gets automatically canceled and I get to a much smaller view of OEB (screenshot 2). I encountered the resolution issue on screenshot 2 a couple of times during badge creation or editing processes. This is probably the same issue that Franzi encountered (#148), but given that the behavior is somewhat different on cell phones, I added this as a new issue.

**Expected behavior**
1. Be able to choose icons when creating a badge on my cell phone
2. Be able to continue the badge creation process even when I don't immediately select "Kamera" or "Dateien"

**Screenshots**
Screenshot 1
![Screenshot_20240408-181119](https://github.com/mint-o-badges/badgr-ui/assets/164183217/f050f684-b84f-4b5f-a387-d6865bd1bca0)

Screenshot 2
![Screenshot_20240408-181011](https://github.com/mint-o-badges/badgr-ui/assets/164183217/fe7c3a6d-9dd7-4676-b172-509e09e1ac59)

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: Huawei Mate 10 Lite
-   OS: Android
-   Browser: Firefox

**Comment by zven** [comment] 2024-04-09 11:57
I had the same issue on an iPhone SE 2020 using the DuckDuckGo browser

**Comment by zven** [comment] 2024-04-15 12:30
Closely related to #149. Whoever is picking this ticket, please talk to @jona159 as well.

**Comment by zven** [comment] 2024-04-17 07:59
Closely related to #149

**Comment by zven** [comment] 2024-04-17 08:28
Duplicate of #149

**Comment by zven** [comment] 2024-04-17 08:28
Duplicate of #149

**Closed by zven** 2024-04-17 08:28 UTC
Labels: bug, test finding
