### ISSUE TITLE
Button needs round corners

### ISSUE THREAD

**Issue by schmidfranzi** [mint-o-badges/badgr-ui#141] opened 2024-04-04 13:39 UTC
**Name the test case**
Layout Landing Page

**Describe the bug**
The first red button "Jetzt Badge erstellen" is missing the round corners - just like the other buttons have

**To Reproduce**

**Expected behavior**
it has round corners

**Screenshots**
<img width="1268" alt="Screenshot 2024-04-04 at 15 30 38" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/7302695d-2c7d-4188-92fd-854cfb43f8c6">
<img width="1268" alt="Screenshot 2024-04-04 at 15 30 38" src="https://github.com/mint-o-badges/badgr-ui/assets/164329233/75ac8b80-9113-4c8f-8f58-b37836123d8e">

**Desktop (please complete the following information; remove if not applicable):**

 - Browser Chrome

**Smartphone (please complete the following information; remove if not applicable):**

**Additional context**
Add any other context about your observations here.

**Comment by Annicelia** [comment] 2024-04-08 13:40
same in MacOS Browser Firefox

**Comment by zven** [comment] 2024-04-08 14:20
Duplicate of #140

**Closed by zven** 2024-04-08 14:20 UTC
Labels: test finding
