### ISSUE TITLE
Unique: Error message for creating a badge

### ISSUE THREAD

**Issue by IngaSchmidt** [mint-o-badges/badgr-ui#568] opened 2024-08-01 10:34 UTC
**Name the test case**
A colleague has tried to create a competence badge

**Describe the bug**
When he clicked on the "Create badge" button, he received an error message (see screenshot). This was on Tuesday, 30 July at around 4.30 pm. The next morning, the process worked flawlessly and he no longer received an error message.

**To Reproduce**
Create badge

**Screenshots**
<img width="586" alt="Bildschirmfoto 2024-07-30 um 16 27 20" src="https://github.com/user-attachments/assets/8deed481-a4e9-4104-9028-999e4b66304c">

**Desktop (please complete the following information; remove if not applicable):**

-   MacBookPro
-   Edge or Firefox (He is not 100% sure)

**Comment by zven** [comment] 2024-11-15 11:34
outdated and duplicate of https://github.com/mint-o-badges/badgr-ui/issues/814

**Closed by zven** 2024-11-15 11:34 UTC
Labels: test finding
